site_name: AionApi
site_description: Backend Go â€” Hexagonal, REST/GraphQL, Observability
repo_name: lechitz/AionApi
repo_url: https://github.com/lechitz/AionApi
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy
    - content.tabs.link
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
#  - GraphQL:
#      - Overview: graphql/index.md
#      - Queries: graphql/queries.md
#      - Mutations: graphql/mutations.md
#      - Types: graphql/types.md
#      - Examples: graphql/examples.md
#      - Collection (Runner): graphql/collection.md
  - Swagger UI: https://lechitz.github.io/AionApi/swagger-ui/
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables